In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
customer_df = pd.read_csv('files_for_lab/we_fn_use_c_marketing_customer_value_analysis.csv')

Find all of the categorical data. Save it in a categorical_df variable.

In [3]:
categorical_df = customer_df.select_dtypes(include=object)

In [5]:
categorical_df.head(30)

,Customer,State,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Location Code,Marital Status,Policy Type,Policy,Renew Offer Type,Sales Channel,Vehicle Class,Vehicle Size
0,BU79786,Washington,No,Basic,Bachelor,2/24/11,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Two-Door Car,Medsize
1,QZ44356,Arizona,No,Extended,Bachelor,1/31/11,Unemployed,F,Suburban,Single,Personal Auto,Personal L3,Offer3,Agent,Four-Door Car,Medsize
2,AI49188,Nevada,No,Premium,Bachelor,2/19/11,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer1,Agent,Two-Door Car,Medsize
3,WW63253,California,No,Basic,Bachelor,1/20/11,Unemployed,M,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,SUV,Medsize
4,HB64268,Washington,No,Basic,Bachelor,2/3/11,Employed,M,Rural,Single,Personal Auto,Personal L1,Offer1,Agent,Four-Door Car,Medsize
5,OC83172,Oregon,Yes,Basic,Bachelor,1/25/11,Employed,F,Rural,Married,Personal Auto,Personal L3,Offer2,Web,Two-Door Car,Medsize
6,XZ87318,Oregon,Yes,Basic,College,2/24/11,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Four-Door Car,Medsize
7,CF85061,Arizona,No,Premium,Master,1/18/11,Unemployed,M,Urban,Single,Corporate Auto,Corporate L3,Offer1,Agent,Four-Door Car,Medsize
8,DY87989,Oregon,Yes,Basic,Bachelor,1/26/11,Medical Leave,M,Suburban,Divorced,Corporate Auto,Corporate L3,Offer1,Agent,Four-Door Car,Medsize
9,BQ94931,Oregon,No,Extended,College,2/17/11,Employed,F,Urban,Married,Special Auto,Special L2,Offer2,Branch,Four-Door Car,Medsize
10,SX51350,California,No,Basic,College,2/21/11,Unemployed,M,Suburban,Single,Personal Auto,Personal L3,Offer1,Agent,Four-Door Car,Small
11,VQ65197,California,No,Basic,College,1/6/11,Unemployed,F,Suburban,Married,Personal Auto,Personal L3,Offer2,Agent,SUV,Medsize
12,DP39365,California,No,Premium,Master,2/6/11,Employed,M,Urban,Married,Corporate Auto,Corporate L1,Offer2,Agent,Four-Door Car,Medsize
13,SJ95423,Arizona,Yes,Basic,High School or Below,1/10/11,Employed,M,Suburban,Married,Corporate Auto,Corporate L3,Offer2,Branch,SUV,Medsize
14,IL66569,California,No,Basic,College,1/18/11,Employed,M,Urban,Single,Corporate Auto,Corporate L3,Offer4,Call Center,Four-Door Car,Medsize
15,BW63560,Oregon,No,Basic,Bachelor,1/17/11,Employed,F,Rural,Married,Corporate Auto,Corporate L2,Offer2,Branch,Four-Door Car,Medsize
16,FV94802,Nevada,No,Basic,High School or Below,2/6/11,Medical Leave,M,Suburban,Married,Personal Auto,Personal L3,Offer2,Call Center,Two-Door Car,Medsize
17,OE15005,California,No,Basic,College,1/5/11,Medical Leave,M,Suburban,Married,Personal Auto,Personal L2,Offer3,Call Center,SUV,Medsize
18,WC83389,Oregon,No,Basic,College,2/27/11,Employed,M,Urban,Married,Personal Auto,Personal L2,Offer2,Branch,Four-Door Car,Medsize
19,FL50705,California,No,Premium,High School or Below,1/14/11,Employed,F,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,Four-Door Car,Small
20,ZK25313,Oregon,No,Basic,High School or Below,2/19/11,Employed,M,Suburban,Single,Personal Auto,Personal L2,Offer1,Branch,Two-Door Car,Medsize
21,SV62436,Washington,No,Extended,Bachelor,1/21/11,Disabled,F,Suburban,Divorced,Personal Auto,Personal L3,Offer4,Call Center,Four-Door Car,Medsize
22,YH23384,Arizona,Yes,Basic,Bachelor,1/26/11,Medical Leave,M,Suburban,Divorced,Personal Auto,Personal L3,Offer1,Agent,Four-Door Car,Medsize
23,TZ98966,Nevada,No,Basic,Bachelor,2/24/11,Unemployed,F,Suburban,Single,Corporate Auto,Corporate L3,Offer1,Branch,Four-Door Car,Medsize
24,HM55802,California,No,Basic,Bachelor,2/5/11,Disabled,F,Suburban,Married,Corporate Auto,Corporate L2,Offer2,Branch,Four-Door Car,Medsize
25,FS42516,Oregon,No,Basic,College,1/29/11,Employed,M,Suburban,Married,Personal Auto,Personal L3,Offer2,Call Center,Four-Door Car,Large
26,US89481,California,No,Premium,Bachelor,2/28/11,Unemployed,F,Suburban,Single,Personal Auto,Personal L3,Offer1,Agent,Four-Door Car,Small
27,HO30839,Washington,No,Extended,Master,2/12/11,Disabled,F,Urban,Married,Corporate Auto,Corporate L1,Offer1,Branch,SUV,Medsize
28,GE62437,Arizona,No,Premium,College,2/2/11,Employed,F,Suburban,Single,Personal Auto,Personal L3,Offer1,Call Center,Four-Door Car,Large
29,EJ77678,Oregon,No,Extended,Master,2/7/11,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer2,Branch,Four-Door Car,Small

Check for NaN values.

In [6]:
categorical_df.isna().sum()

Customer             0
State                0
Response             0
Coverage             0
Education            0
Effective To Date    0
EmploymentStatus     0
Gender               0
Location Code        0
Marital Status       0
Policy Type          0
Policy               0
Renew Offer Type     0
Sales Channel        0
Vehicle Class        0
Vehicle Size         0
dtype: int64

Check all unique values of columns.

In [7]:
for column in categorical_df:
    display(categorical_df[column].value_counts(dropna = False))

BU79786    1
PU81096    1
CO75086    1
WW52683    1
XO38850    1
          ..
HS14476    1
YL91587    1
CT18212    1
EW35231    1
Y167826    1
Name: Customer, Length: 9134, dtype: int64

California    3150
Oregon        2601
Arizona       1703
Nevada         882
Washington     798
Name: State, dtype: int64

No     7826
Yes    1308
Name: Response, dtype: int64

Basic       5568
Extended    2742
Premium      824
Name: Coverage, dtype: int64

Bachelor                2748
College                 2681
High School or Below    2622
Master                   741
Doctor                   342
Name: Education, dtype: int64

1/10/11    195
1/27/11    194
2/14/11    186
1/26/11    181
1/17/11    180
1/19/11    179
1/31/11    178
1/3/11     178
1/20/11    173
2/26/11    169
1/28/11    169
2/19/11    168
1/5/11     167
2/27/11    167
1/11/11    166
2/4/11     164
2/10/11    161
2/28/11    161
1/2/11     160
1/21/11    160
1/29/11    160
2/22/11    158
2/5/11     158
2/3/11     158
2/7/11     157
2/12/11    156
1/23/11    155
2/1/11     154
1/18/11    154
1/15/11    153
1/14/11    152
2/11/11    151
1/7/11     151
1/25/11    151
2/25/11    149
1/8/11     149
2/18/11    149
2/2/11     149
1/1/11     148
2/21/11    148
1/24/11    147
1/9/11     146
1/30/11    145
1/13/11    145
2/6/11     144
1/6/11     143
2/23/11    143
1/16/11    142
2/16/11    139
2/13/11    139
2/24/11    139
2/9/11     137
2/17/11    136
1/22/11    136
2/8/11     134
2/20/11    132
2/15/11    130
1/12/11    126
1/4/11     115
Name: Effective To Date, dtype: int64

Employed         5698
Unemployed       2317
Medical Leave     432
Disabled          405
Retired           282
Name: EmploymentStatus, dtype: int64

F    4658
M    4476
Name: Gender, dtype: int64

Suburban    5779
Rural       1773
Urban       1582
Name: Location Code, dtype: int64

Married     5298
Single      2467
Divorced    1369
Name: Marital Status, dtype: int64

Personal Auto     6788
Corporate Auto    1968
Special Auto       378
Name: Policy Type, dtype: int64

Personal L3     3426
Personal L2     2122
Personal L1     1240
Corporate L3    1014
Corporate L2     595
Corporate L1     359
Special L2       164
Special L3       148
Special L1        66
Name: Policy, dtype: int64

Offer1    3752
Offer2    2926
Offer3    1432
Offer4    1024
Name: Renew Offer Type, dtype: int64

Agent          3477
Branch         2567
Call Center    1765
Web            1325
Name: Sales Channel, dtype: int64

Four-Door Car    4621
Two-Door Car     1886
SUV              1796
Sports Car        484
Luxury SUV        184
Luxury Car        163
Name: Vehicle Class, dtype: int64

Medsize    6424
Small      1764
Large       946
Name: Vehicle Size, dtype: int64

Check dtypes. Do they all make sense as categorical data?

In [8]:
categorical_df.dtypes

Customer             object
State                object
Response             object
Coverage             object
Education            object
Effective To Date    object
EmploymentStatus     object
Gender               object
Location Code        object
Marital Status       object
Policy Type          object
Policy               object
Renew Offer Type     object
Sales Channel        object
Vehicle Class        object
Vehicle Size         object
dtype: object

Column Effective To Date has values as dates it is not useful as categorical data

Does any column contain alpha and numeric data? Decide how to clean it.

As we did in the numerical lab, we can transform effective to date to datetime

Would you choose to do anything else to clean or wrangle the categorical data? Comment your decisions.

Compare policy_type and policy. What information is contained in these columns. Can you identify what is important?

'Policy' and 'Policy Type' both specify whether an insurance is 'Personal', 'Corporate', or 'Special'. The important part is to figure out what is L1,L2...

Check number of unique values in each column, can they be combined in any way to ease encoding? Comment your thoughts and make those changes.

In [9]:
for column in categorical_df:
    print(column, len(categorical_df[column].value_counts()))

Customer 9134
State 5
Response 2
Coverage 3
Education 5
Effective To Date 59
EmploymentStatus 5
Gender 2
Location Code 3
Marital Status 3
Policy Type 3
Policy 9
Renew Offer Type 4
Sales Channel 4
Vehicle Class 6
Vehicle Size 3

column 'customer' can be dropped because they are unique values 
as said earlier. effective to date can be either transformed or if it is not needed dropped